### ISSUE TITLE
[Enhancement] Improve tag creation pipeline to skip repositories without write permission for the bot account

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/opensearch-build#1860]
As of now, the release tag creation will fail the build if the bot account does not have permission to write in any repository.

This requires our team member with access to manually create a tag on those repos.

We should let the pipeline skip these repos, and output a list of repos that requires to add the bot with write access, and we can manually create the tags after the release pipeline run.

### Acceptance Criteria

- We would want to create tags for all repositories, if creation fails, the repository should be skipped and continue for the remaining repositories. The job should then fail listing down the failed repositories.

**Comment by dblock** [comment]
I think it's a bad idea. Permissions should be fixed anyway, and the workflow can be rerun as many times as needed as it skips correct existing tags. If you stop failing it, we'll never know that permissions are missing.

**Comment by bbarani** [comment]
We are not going to stop failing rather we dont want the process to fail in the middle of the tagging process since it doesn't have access to those repos. The job will still fail listing the repos that has issue but it wont affect the other repos not affected due to access issues.

**Comment by zelinh** [comment]
If the pipeline failed, we should always rerun the workflow to make sure tags are successfully created on other components until the job passes. 
One drawback of current workflow I think is that we will need to rerun the job more than 2 times if there are multiple repos that bot doesn't have write access on.

**Comment by abhinavGupta16** [comment]
[triage] We would want to create tags for all repositories, if creation fails, the repository should be skipped and continue for the remaining repositories. The job should then fail listing down the failed repositories.

**Comment by zelinh** [comment]
Closing this issue as this enhancement have been implemented with PR linked above.
